# Generated by Django 6.0.5 on 2026-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funkos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funko',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si lo desmarcás, el Funko se da de baja: deja de mostrarse en la tienda pero NO se elimina de la base de datos.', verbose_name='¿Activo?'),
        ),
    ]
