# Generated by Django 6.0.5 on 2026-05-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Versión URL-amigable del nombre (ej: "series-de-tv")', max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franquicias', to='Funkos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Franquicia',
                'verbose_name_plural': 'Franquicias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Versión URL del nombre (ej: "eleven-stranger-things")', max_length=180, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='funkos/', verbose_name='Imagen')),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('rara', 'Rara'), ('exclusiva', 'Exclusiva'), ('limitada', 'Edición limitada')], default='comun', max_length=20, verbose_name='Rareza')),
                ('es_exclusivo', models.BooleanField(default=False, help_text='Marcalo si es un Funko exclusivo o de edición especial', verbose_name='¿Es exclusivo?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funkos', to='Funkos.categoria', verbose_name='Categoría')),
                ('franquicia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funkos', to='Funkos.franquicia', verbose_name='Franquicia')),
            ],
            options={
                'verbose_name': 'Funko',
                'verbose_name_plural': 'Funkos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
